obj-$(CONFIG_MSM_HOTPLUG)         		+= msm_hotplug.o
obj-$(CONFIG_LAZYPLUG)				+= lazyplug.o
obj-$(CONFIG_ALUCARD_HOTPLUG) 			+= alucard_hotplug.o
obj-$(CONFIG_THUNDERPLUG_CONTROL) 		+= thunderplug.o
