obj-$(CONFIG_LAZYPLUG)				+= lazyplug.o
obj-$(CONFIG_ALUCARD_HOTPLUG) 			+= alucard_hotplug.o
obj-$(CONFIG_THUNDERPLUG_CONTROL) 		+= thunderplug.o
obj-$(CONFIG_INTELLI_HOTPLUG)	  		+= intelli_hotplug.o
obj-$(CONFIG_AUTOSMP) 				+= autosmp.o 
obj-$(CONFIG_MAKO_HOTPLUG) 			+= mako_hotplug.o
